services:
  app:
    image: openjdk:17-jdk-slim
    working_dir: /app
    volumes:
      - ./target/task-tracker-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: password
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/tasktracker?authSource=admin

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"